package com.fbdblog.qtype.util;


import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.Iterator;

import org.apache.log4j.Logger;
import com.fbdblog.dao.App;
import com.fbdblog.dao.User;
import com.fbdblog.dao.Post;
import com.fbdblog.dao.Question;
import com.fbdblog.qtype.def.ComponentTypes;
import com.fbdblog.qtype.def.Component;
import com.fbdblog.util.Str;

/**
 * User: Joe Reger Jr
 * Date: Jul 6, 2006
 * Time: 1:36:39 PM
 */
public class AppTemplateProcessor {

    private App app;
    private User user;
    private Post post;

    Logger logger = Logger.getLogger(this.getClass().getName());

    public AppTemplateProcessor(App app, User user, Post post){
        this.app = app;
        this.user = user;
        this.post = post;
    }

    public String getHtmlForInput(boolean makeHttpsIfSSLIsOn){
        StringBuffer out = new StringBuffer();
        String template = "";
        if (template==null){
            template = "";
        }
        //@todo implement screen to allow for app template
        if (template.equals("")){
            template = getAutoGeneratedTemplateForApp(app);
        }
        template = appendExtraQuestionsIfNecessary(app, template);

        Pattern p = Pattern.compile("\\<\\$(.|\\n)*?\\$\\>");
        Matcher m = p.matcher(template);
        while(m.find()) {
            ComponentTypes ct = new ComponentTypes();
            Component component = ct.getByTagSyntax(m.group(), app, post, user);
            if (component!=null){
                m.appendReplacement(out, Str.cleanForAppendreplacement(component.getHtmlForInput() + "<br>"));
            }
        }
        try{
            m.appendTail(out);
        } catch (Exception e){
            //Do nothing... just null pointer
        }
        return "<div style=\"background : #ffffff; border: 0px solid #ffffff; padding : 5px; width : 220px; overflow : auto;\">"+out.toString()+"</div>";
    }


    public static String getAutoGeneratedTemplateForApp(App app){
        StringBuffer out = new StringBuffer();
        //HibernateUtil.getSession().saveOrUpdate(app);
        for (Iterator<Question> iterator = app.getQuestions().iterator(); iterator.hasNext();) {
            Question question = iterator.next();
            out.append("\n"+"<p>");
            out.append("<$question_"+question.getQuestionid()+"$>");
            out.append("</p>");
        }
        return appendExtraQuestionsIfNecessary(app, out.toString());
    }

    public static String appendExtraQuestionsIfNecessary(App app, String currentTemplate){
        StringBuffer out = new StringBuffer();
        Logger logger = Logger.getLogger(AppTemplateProcessor.class);
        if (currentTemplate!=null){
            out.append(currentTemplate);
        }
        for (Iterator<Question> iterator = app.getQuestions().iterator(); iterator.hasNext();) {
            Question question = iterator.next();
            String qtag = "<$question_"+question.getQuestionid()+"$>";
            if (currentTemplate==null || currentTemplate.indexOf(qtag)<0){
                out.append("\n"+"<p>");
                out.append("<$question_"+question.getQuestionid()+"$>");
                out.append("</p>");
            }
        }
        return out.toString();
    }


    public App getApp() {
        return app;
    }

    public User getUser() {
        return user;
    }

    public Post getPost() {
        return post;
    }
}
