package com.fbdblog.dao;
// Generated Apr 17, 2006 3:45:24 PM by Hibernate Tools 3.1.0.beta4

import com.fbdblog.util.GeneralException;
import com.fbdblog.dao.hibernate.BasePersistentClass;
import com.fbdblog.dao.hibernate.RegerEntity;
import com.fbdblog.dao.hibernate.HibernateUtil;
import com.fbdblog.dao.hibernate.AuthControlled;

import java.util.Set;
import java.util.HashSet;
import java.util.Date;

import org.apache.log4j.Logger;


/**
 * Survey generated by hbm2java
 */

public class App extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {



     // Fields
     private int appid;
     private String title;
     private String description;
     private String facebookappname;
     private String facebookapikey;
     private String facebookapisecret;
     private String facebookinfinitesessionkey;
     private int primarychartid;
     private String minifeedtemplate;
     private boolean crosspromote;
     private String adglobalheader;
     private String adpostsave;
     private String adhistoryright;
     private String adunderchart;
     private Date createdate;
     private boolean isdefaultprivate;


     private Set<Question> questions = new HashSet<Question>();

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static App get(int id) {
        Logger logger = Logger.getLogger("com.fbdblog.dao.App");
        try {
            logger.debug("App.get(" + id + ") called.");
            App obj = (App) HibernateUtil.getSession().get(App.class, id);
            if (obj == null) {
                logger.debug("App.get(" + id + ") returning new instance because hibernate returned null.");
                return new App();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.fbdblog.dao.App", ex);
            return new App();
        }
    }

    // Constructors

    /** default constructor */
    public App() {
    }




    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }







    // Property accessors


    public int getAppid() {
        return appid;
    }

    public void setAppid(int appid) {
        this.appid = appid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }



    public Set<Question> getQuestions() {
        return questions;
    }

    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }


    public String getFacebookappname() {
        return facebookappname;
    }

    public void setFacebookappname(String facebookappname) {
        this.facebookappname = facebookappname;
    }

    public String getFacebookapikey() {
        return facebookapikey;
    }

    public void setFacebookapikey(String facebookapikey) {
        this.facebookapikey = facebookapikey;
    }

    public String getFacebookapisecret() {
        return facebookapisecret;
    }

    public void setFacebookapisecret(String facebookapisecret) {
        this.facebookapisecret = facebookapisecret;
    }


    public int getPrimarychartid() {
        return primarychartid;
    }

    public void setPrimarychartid(int primarychartid) {
        this.primarychartid=primarychartid;
    }


    public String getMinifeedtemplate() {
        return minifeedtemplate;
    }

    public void setMinifeedtemplate(String minifeedtemplate) {
        this.minifeedtemplate=minifeedtemplate;
    }

    public boolean getCrosspromote() {
        return crosspromote;
    }

    public void setCrosspromote(boolean crosspromote) {
        this.crosspromote=crosspromote;
    }

    public String getAdglobalheader() {
        return adglobalheader;
    }

    public void setAdglobalheader(String adglobalheader) {
        this.adglobalheader=adglobalheader;
    }

    public String getAdpostsave() {
        return adpostsave;
    }

    public void setAdpostsave(String adpostsave) {
        this.adpostsave=adpostsave;
    }

    public String getAdhistoryright() {
        return adhistoryright;
    }

    public void setAdhistoryright(String adhistoryright) {
        this.adhistoryright=adhistoryright;
    }

    public String getAdunderchart() {
        return adunderchart;
    }

    public void setAdunderchart(String adunderchart) {
        this.adunderchart=adunderchart;
    }

    public String getFacebookinfinitesessionkey() {
        return facebookinfinitesessionkey;
    }

    public void setFacebookinfinitesessionkey(String facebookinfinitesessionkey) {
        this.facebookinfinitesessionkey=facebookinfinitesessionkey;
    }

    public Date getCreatedate() {
        return createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate=createdate;
    }

    public boolean getIsdefaultprivate() {
        return isdefaultprivate;
    }

    public void setIsdefaultprivate(boolean isdefaultprivate) {
        this.isdefaultprivate=isdefaultprivate;
    }
}
