package com.fbdblog.dao;

import com.fbdblog.dao.hibernate.BasePersistentClass;
import com.fbdblog.dao.hibernate.RegerEntity;
import com.fbdblog.dao.hibernate.AuthControlled;
import com.fbdblog.dao.hibernate.HibernateUtil;
import com.fbdblog.util.GeneralException;
import org.apache.log4j.Logger;

import java.util.Date;

/**
 * User generated by hbm2java
 */

public class Calculation extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


     private int calculationid;
     private int questionid;
     private int userid;
     private int calculationtype;
     private int calctimeperiodid;
     private Date recordeddate;
     private String calctimeperiodkey;
     private double value;


    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Calculation get(int id) {
        Logger logger = Logger.getLogger("com.fbdblog.dao.Calculation");
        try {
            logger.debug("Calculation.get(" + id + ") called.");
            Calculation obj = (Calculation) HibernateUtil.getSession().get(Calculation.class, id);
            if (obj == null) {
                logger.debug("Calculation.get(" + id + ") returning new instance because hibernate returned null.");
                return new Calculation();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.fbdblog.dao.Calculation", ex);
            return new Calculation();
        }
    }

    // Constructors

    /** default constructor */
    public Calculation() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }





    // Property accessors


    public int getCalculationid() {
        return calculationid;
    }

    public void setCalculationid(int calculationid) {
        this.calculationid=calculationid;
    }

    public int getQuestionid() {
        return questionid;
    }

    public void setQuestionid(int questionid) {
        this.questionid=questionid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid=userid;
    }

    public int getCalculationtype() {
        return calculationtype;
    }

    public void setCalculationtype(int calculationtype) {
        this.calculationtype=calculationtype;
    }

    public int getCalctimeperiodid() {
        return calctimeperiodid;
    }

    public void setCalctimeperiodid(int calctimeperiodid) {
        this.calctimeperiodid=calctimeperiodid;
    }

    public String getCalctimeperiodkey() {
        return calctimeperiodkey;
    }

    public void setCalctimeperiodkey(String calctimeperiodkey) {
        this.calctimeperiodkey=calctimeperiodkey;
    }

    public double getValue() {
        return value;
    }

    public void setValue(double value) {
        this.value=value;
    }

    public Date getRecordeddate() {
        return recordeddate;
    }

    public void setRecordeddate(Date recordeddate) {
        this.recordeddate=recordeddate;
    }
}
