package com.fbdblog.dao;

import com.fbdblog.dao.hibernate.BasePersistentClass;
import com.fbdblog.dao.hibernate.RegerEntity;
import com.fbdblog.dao.hibernate.AuthControlled;
import com.fbdblog.dao.hibernate.HibernateUtil;
import com.fbdblog.util.GeneralException;

import java.util.Set;
import java.util.HashSet;

import org.apache.log4j.Logger;

/**
 * Survey generated by hbm2java
 */

public class Chart extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {



     // Fields
     private int chartid;
     private int appid;
     private String name;
     private int xquestionid;
     private int yaxiswhattodo;
     private int charttype;
     private int daterange;
     private int lastxdays;
     private int lastxweeks;
     private int lastxmonths;
     private int lastxyears;
     private int daterangefromyyyy;
     private int daterangefrommm;
     private int daterangefromdd;
     private int daterangetoyyyy;
     private int daterangetomm;
     private int daterangetodd;

     private Set<Chartyaxis> chartyaxes = new HashSet<Chartyaxis>();


    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Chart get(int id) {
        Logger logger = Logger.getLogger("com.fbdblog.dao.App");
        try {
            logger.debug("App.get(" + id + ") called.");
            Chart obj = (Chart) HibernateUtil.getSession().get(Chart.class, id);
            if (obj == null) {
                logger.debug("App.get(" + id + ") returning new instance because hibernate returned null.");
                return new Chart();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.fbdblog.dao.App", ex);
            return new Chart();
        }
    }

    // Constructors

    /** default constructor */
    public Chart() {
    }




    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }


    public int getChartid() {
        return chartid;
    }

    public void setChartid(int chartid) {
        this.chartid = chartid;
    }

    public int getAppid() {
        return appid;
    }

    public void setAppid(int appid) {
        this.appid = appid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getXquestionid() {
        return xquestionid;
    }

    public void setXquestionid(int xquestionid) {
        this.xquestionid = xquestionid;
    }

    public int getYaxiswhattodo() {
        return yaxiswhattodo;
    }

    public void setYaxiswhattodo(int yaxiswhattodo) {
        this.yaxiswhattodo = yaxiswhattodo;
    }

    public int getCharttype() {
        return charttype;
    }

    public void setCharttype(int charttype) {
        this.charttype = charttype;
    }

    public int getDaterange() {
        return daterange;
    }

    public void setDaterange(int daterange) {
        this.daterange = daterange;
    }

    public int getLastxdays() {
        return lastxdays;
    }

    public void setLastxdays(int lastxdays) {
        this.lastxdays = lastxdays;
    }

    public int getLastxweeks() {
        return lastxweeks;
    }

    public void setLastxweeks(int lastxweeks) {
        this.lastxweeks = lastxweeks;
    }

    public int getLastxmonths() {
        return lastxmonths;
    }

    public void setLastxmonths(int lastxmonths) {
        this.lastxmonths = lastxmonths;
    }

    public int getLastxyears() {
        return lastxyears;
    }

    public void setLastxyears(int lastxyears) {
        this.lastxyears = lastxyears;
    }

    public int getDaterangefromyyyy() {
        return daterangefromyyyy;
    }

    public void setDaterangefromyyyy(int daterangefromyyyy) {
        this.daterangefromyyyy = daterangefromyyyy;
    }

    public int getDaterangefrommm() {
        return daterangefrommm;
    }

    public void setDaterangefrommm(int daterangefrommm) {
        this.daterangefrommm = daterangefrommm;
    }

    public int getDaterangefromdd() {
        return daterangefromdd;
    }

    public void setDaterangefromdd(int daterangefromdd) {
        this.daterangefromdd = daterangefromdd;
    }

    public int getDaterangetoyyyy() {
        return daterangetoyyyy;
    }

    public void setDaterangetoyyyy(int daterangetoyyyy) {
        this.daterangetoyyyy = daterangetoyyyy;
    }

    public int getDaterangetomm() {
        return daterangetomm;
    }

    public void setDaterangetomm(int daterangetomm) {
        this.daterangetomm = daterangetomm;
    }

    public int getDaterangetodd() {
        return daterangetodd;
    }

    public void setDaterangetodd(int daterangetodd) {
        this.daterangetodd = daterangetodd;
    }

    public Set<Chartyaxis> getChartyaxes() {
        return chartyaxes;
    }

    public void setChartyaxes(Set<Chartyaxis> chartyaxes) {
        this.chartyaxes = chartyaxes;
    }
}
