package com.fbdblog.dao;

import com.fbdblog.dao.hibernate.BasePersistentClass;
import com.fbdblog.dao.hibernate.RegerEntity;
import com.fbdblog.dao.hibernate.HibernateUtil;
import com.fbdblog.dao.hibernate.AuthControlled;
import com.fbdblog.util.GeneralException;

import java.util.Date;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Error extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {

     public static int STATUS_NEW = 1;
     public static int STATUS_OLD = 0;

    // Fields
     private int errorid;
     private String error;
     private int level;
     private Date date;
     private int status;


    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Error get(int id) {
        Logger logger = Logger.getLogger("com.fbdblog.dao.Error");
        try {
            logger.debug("Error.get(" + id + ") called.");
            Error obj = (Error) HibernateUtil.getSession().get(Error.class, id);
            if (obj == null) {
                logger.debug("Error.get(" + id + ") returning new instance because hibernate returned null.");
                return new Error();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.fbdblog.dao.Error", ex);
            return new Error();
        }
    }

    // Constructors

    /** default constructor */
    public Error() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors


    public int getErrorid() {
        return errorid;
    }

    public void setErrorid(int errorid) {
        this.errorid = errorid;
    }

    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }
}
