package com.fbdblog.dao;

import com.fbdblog.dao.hibernate.BasePersistentClass;
import com.fbdblog.dao.hibernate.RegerEntity;
import com.fbdblog.dao.hibernate.HibernateUtil;
import com.fbdblog.dao.hibernate.AuthControlled;
import com.fbdblog.util.GeneralException;
import org.apache.log4j.Logger;

import java.util.Date;
import java.util.Set;
import java.util.HashSet;

/**
 * Blogger generated by hbm2java
 */

public class Post extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


    // Fields
     private int postid;
     private int appid;
     private int userid;
     private Date postdate;
     private String notes;
     private Set<Postanswer> postanswers = new HashSet<Postanswer>();

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Post get(int id) {
        Logger logger = Logger.getLogger("com.fbdblog.dao.Post");
        try {
            logger.debug("Post.get(" + id + ") called.");
            Post obj = (Post) HibernateUtil.getSession().get(Post.class, id);
            if (obj == null) {
                logger.debug("Post.get(" + id + ") returning new instance because hibernate returned null.");
                return new Post();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.fbdblog.dao.Post", ex);
            return new Post();
        }
    }

    // Constructors

    /** default constructor */
    public Post() {
    }


    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }



    // Property accessors


    public int getPostid() {
        return postid;
    }

    public void setPostid(int postid) {
        this.postid = postid;
    }


    public int getAppid() {
        return appid;
    }

    public void setAppid(int appid) {
        this.appid = appid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }


    public Date getPostdate() {
        return postdate;
    }

    public void setPostdate(Date postdate) {
        this.postdate = postdate;
    }

    public Set<Postanswer> getPostanswers() {
        return postanswers;
    }

    public void setPostanswers(Set<Postanswer> postanswers) {
        this.postanswers = postanswers;
    }


    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes=notes;
    }
}
