package com.fbdblog.dao;

import com.fbdblog.dao.hibernate.BasePersistentClass;
import com.fbdblog.dao.hibernate.RegerEntity;
import com.fbdblog.dao.hibernate.HibernateUtil;
import com.fbdblog.util.GeneralException;
import com.fbdblog.dao.hibernate.AuthControlled;
import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Postanswer extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


    // Fields
     private int postanswerid;
     private int postid;
     private int questionid;
     private int userid;
     private String name;
     private String value;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Postanswer get(int id) {
        Logger logger = Logger.getLogger("com.fbdblog.dao.Questionresponse");
        try {
            logger.debug("Questionresponse.get(" + id + ") called.");
            Postanswer obj = (Postanswer) HibernateUtil.getSession().get(Postanswer.class, id);
            if (obj == null) {
                logger.debug("Questionresponse.get(" + id + ") returning new instance because hibernate returned null.");
                return new Postanswer();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.fbdblog.dao.Questionresponse", ex);
            return new Postanswer();
        }
    }

    // Constructors

    /** default constructor */
    public Postanswer() {
    }


    public boolean canRead(User user){
        Question question = Question.get(questionid);
        return question.canRead(user);
    }

    public boolean canEdit(User user){
        return canRead(user);
    }



    // Property accessors


    public int getPostanswerid() {
        return postanswerid;
    }

    public void setPostanswerid(int postanswerid) {
        this.postanswerid = postanswerid;
    }

    public int getPostid() {
        return postid;
    }

    public void setPostid(int postid) {
        this.postid = postid;
    }

    public int getQuestionid() {
        return questionid;
    }

    public void setQuestionid(int questionid) {
        this.questionid = questionid;
    }


    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }


}
