package com.fbdblog.dao;

import com.fbdblog.dao.hibernate.BasePersistentClass;
import com.fbdblog.dao.hibernate.RegerEntity;
import com.fbdblog.dao.hibernate.AuthControlled;
import com.fbdblog.dao.hibernate.HibernateUtil;
import com.fbdblog.util.GeneralException;
import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Questionuserconfig extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


    // Fields
     private int questionuserconfigid;
     private int questionid;
     private int userid;
     private String name;
     private String value;


    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Questionuserconfig get(int id) {
        Logger logger = Logger.getLogger("com.fbdblog.dao.Questionuserconfig");
        try {
            logger.debug("Questionuserconfig.get(" + id + ") called.");
            Questionuserconfig obj = (Questionuserconfig) HibernateUtil.getSession().get(Questionuserconfig.class, id);
            if (obj == null) {
                logger.debug("Questionuserconfig.get(" + id + ") returning new instance because hibernate returned null.");
                return new Questionuserconfig();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.fbdblog.dao.Questionuserconfig", ex);
            return new Questionuserconfig();
        }
    }

    // Constructors

    /** default constructor */
    public Questionuserconfig() {
    }


    public boolean canRead(User user){
        Question question = Question.get(questionid);
        return question.canRead(user);
    }

    public boolean canEdit(User user){
        return canRead(user);
    }



    // Property accessors

    public int getQuestionuserconfigid() {
        return questionuserconfigid;
    }

    public void setQuestionuserconfigid(int questionuserconfigid) {
        this.questionuserconfigid = questionuserconfigid;
    }

    public int getQuestionid() {
        return questionid;
    }

    public void setQuestionid(int questionid) {
        this.questionid = questionid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }


}
