package com.fbdblog.dao;

import com.fbdblog.dao.hibernate.BasePersistentClass;
import com.fbdblog.dao.hibernate.RegerEntity;
import com.fbdblog.dao.hibernate.AuthControlled;
import com.fbdblog.dao.hibernate.HibernateUtil;
import com.fbdblog.util.GeneralException;
import org.apache.log4j.Logger;

/**
 * User generated by hbm2java
 */

public class Questioncalc extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


     private int questioncalcid;
     private int questionid;
     private int calculationtype;
     private int calctimeperiodid;
     private String name;


    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Questioncalc get(int id) {
        Logger logger = Logger.getLogger("com.fbdblog.dao.Questioncalc");
        try {
            logger.debug("Questioncalc.get(" + id + ") called.");
            Questioncalc obj = (Questioncalc) HibernateUtil.getSession().get(Questioncalc.class, id);
            if (obj == null) {
                logger.debug("Questioncalc.get(" + id + ") returning new instance because hibernate returned null.");
                return new Questioncalc();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.fbdblog.dao.Questioncalc", ex);
            return new Questioncalc();
        }
    }

    // Constructors

    /** default constructor */
    public Questioncalc() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }





    // Property accessors


    public int getQuestioncalcid() {
        return questioncalcid;
    }

    public void setQuestioncalcid(int questioncalcid) {
        this.questioncalcid=questioncalcid;
    }

    public int getQuestionid() {
        return questionid;
    }

    public void setQuestionid(int questionid) {
        this.questionid=questionid;
    }

    public int getCalculationtype() {
        return calculationtype;
    }

    public void setCalculationtype(int calculationtype) {
        this.calculationtype=calculationtype;
    }

    public int getCalctimeperiodid() {
        return calctimeperiodid;
    }

    public void setCalctimeperiodid(int calctimeperiodid) {
        this.calctimeperiodid=calctimeperiodid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name=name;
    }
}
