package com.fbdblog.dao;

import com.fbdblog.dao.hibernate.BasePersistentClass;
import com.fbdblog.dao.hibernate.RegerEntity;
import com.fbdblog.dao.hibernate.AuthControlled;
import com.fbdblog.dao.hibernate.HibernateUtil;
import com.fbdblog.util.GeneralException;

import java.util.Date;

import org.apache.log4j.Logger;

/**
 * User generated by hbm2java
 */

public class Supportissuecomm extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


     private int supportissuecommid;
     private int supportissueid;
     private int userid;
     private Date datetime;
     private String notes;


    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Supportissuecomm get(int id) {
        Logger logger = Logger.getLogger("com.fbdblog.dao.Supportissuecomm");
        try {
            logger.debug("Supportissuecomm.get(" + id + ") called.");
            Supportissuecomm obj = (Supportissuecomm) HibernateUtil.getSession().get(Supportissuecomm.class, id);
            if (obj == null) {
                logger.debug("Supportissuecomm.get(" + id + ") returning new instance because hibernate returned null.");
                return new Supportissuecomm();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.fbdblog.dao.Supportissuecomm", ex);
            return new Supportissuecomm();
        }
    }

    // Constructors

    /** default constructor */
    public Supportissuecomm() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }





    // Property accessors


    public int getSupportissuecommid() {
        return supportissuecommid;
    }

    public void setSupportissuecommid(int supportissuecommid) {
        this.supportissuecommid=supportissuecommid;
    }

    public int getSupportissueid() {
        return supportissueid;
    }

    public void setSupportissueid(int supportissueid) {
        this.supportissueid=supportissueid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid=userid;
    }

    public Date getDatetime() {
        return datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime=datetime;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes=notes;
    }
}
