package com.fbdblog.dao;

import com.fbdblog.dao.hibernate.BasePersistentClass;
import com.fbdblog.dao.hibernate.RegerEntity;
import com.fbdblog.dao.hibernate.HibernateUtil;
import com.fbdblog.dao.hibernate.AuthControlled;
import com.fbdblog.util.GeneralException;
import org.apache.log4j.Logger;

import java.util.Iterator;

/**
 * Userrole generated by hbm2java
 */

public class Systemprop extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


    // Fields

     private int systempropid;
     private String name;
     private String value;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Systemprop get(int id) {
        Logger logger = Logger.getLogger("com.fbdblog.dao.Systemprop");
        try {
            logger.debug("Systemprop.get(" + id + ") called.");
            Systemprop obj = (Systemprop) HibernateUtil.getSession().get(Systemprop.class, id);
            if (obj == null) {
                logger.debug("Systemprop.get(" + id + ") returning new instance because hibernate returned null.");
                return new Systemprop();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.fbdblog.dao.Systemprop", ex);
            return new Systemprop();
        }
    }

    // Constructors

    /** default constructor */
    public Systemprop() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }


    public int getSystempropid() {
        return systempropid;
    }

    public void setSystempropid(int systempropid) {
        this.systempropid = systempropid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
