package com.fbdblog.dao;

import com.fbdblog.dao.hibernate.BasePersistentClass;
import com.fbdblog.dao.hibernate.RegerEntity;
import com.fbdblog.dao.hibernate.AuthControlled;
import com.fbdblog.dao.hibernate.HibernateUtil;
import com.fbdblog.util.GeneralException;

import java.util.Date;

import org.apache.log4j.Logger;

/**
 * User generated by hbm2java
 */

public class Throwdown extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


     private int throwdownid;
     private int fromuserid;
     private String tofacebookuid;
     private int touserid;
     private int appid;
     private boolean isaccepted;
     private boolean isdeclined;
     private Date createdate;
     private Date enddate;
     private int questionid;
     private int questioncalcid;
     private boolean isgreaterthan;
     private String name;


    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Throwdown get(int id) {
        Logger logger = Logger.getLogger("com.fbdblog.dao.Throwdown");
        try {
            logger.debug("Throwdown.get(" + id + ") called.");
            Throwdown obj = (Throwdown) HibernateUtil.getSession().get(Throwdown.class, id);
            if (obj == null) {
                logger.debug("Throwdown.get(" + id + ") returning new instance because hibernate returned null.");
                return new Throwdown();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.fbdblog.dao.Throwdown", ex);
            return new Throwdown();
        }
    }

    // Constructors

    /** default constructor */
    public Throwdown() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }





    // Property accessors


    public int getThrowdownid() {
        return throwdownid;
    }

    public void setThrowdownid(int throwdownid) {
        this.throwdownid=throwdownid;
    }

    public int getFromuserid() {
        return fromuserid;
    }

    public void setFromuserid(int fromuserid) {
        this.fromuserid=fromuserid;
    }


    public String getTofacebookuid() {
        return tofacebookuid;
    }

    public void setTofacebookuid(String tofacebookuid) {
        this.tofacebookuid=tofacebookuid;
    }

    public int getTouserid() {
        return touserid;
    }

    public void setTouserid(int touserid) {
        this.touserid=touserid;
    }

    public int getAppid() {
        return appid;
    }

    public void setAppid(int appid) {
        this.appid=appid;
    }

    public boolean getIsaccepted() {
        return isaccepted;
    }

    public void setIsaccepted(boolean isaccepted) {
        this.isaccepted=isaccepted;
    }

    public boolean getIsdeclined() {
        return isdeclined;
    }

    public void setIsdeclined(boolean isdeclined) {
        this.isdeclined=isdeclined;
    }

    public Date getCreatedate() {
        return createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate=createdate;
    }

    public Date getEnddate() {
        return enddate;
    }

    public void setEnddate(Date enddate) {
        this.enddate=enddate;
    }

    public int getQuestionid() {
        return questionid;
    }

    public void setQuestionid(int questionid) {
        this.questionid=questionid;
    }

    public int getQuestioncalcid() {
        return questioncalcid;
    }

    public void setQuestioncalcid(int questioncalcid) {
        this.questioncalcid=questioncalcid;
    }

    public boolean getIsgreaterthan() {
        return isgreaterthan;
    }

    public void setIsgreaterthan(boolean isgreaterthan) {
        this.isgreaterthan=isgreaterthan;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name=name;
    }
}
