package com.fbdblog.dao;

import com.fbdblog.dao.hibernate.BasePersistentClass;
import com.fbdblog.dao.hibernate.RegerEntity;
import com.fbdblog.dao.hibernate.AuthControlled;
import com.fbdblog.dao.hibernate.HibernateUtil;
import com.fbdblog.util.GeneralException;
import org.apache.log4j.Logger;

import java.util.Date;

/**
 * User generated by hbm2java
 */

public class Userappactivity extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


     private int userappactivityid;
     private int userid;
     private int appid;
     private Date date;
     private int year;
     private int month;
     private boolean isinstall;
     private boolean isuninstall;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Userappactivity get(int id) {
        Logger logger = Logger.getLogger("com.fbdblog.dao.Userappactivity");
        try {
            logger.debug("Userappactivity.get(" + id + ") called.");
            Userappactivity obj = (Userappactivity) HibernateUtil.getSession().get(Userappactivity.class, id);
            if (obj == null) {
                logger.debug("Userappactivity.get(" + id + ") returning new instance because hibernate returned null.");
                return new Userappactivity();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.fbdblog.dao.Userappactivity", ex);
            return new Userappactivity();
        }
    }

    // Constructors

    /** default constructor */
    public Userappactivity() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }





    // Property accessors


    public int getUserappactivityid() {
        return userappactivityid;
    }

    public void setUserappactivityid(int userappactivityid) {
        this.userappactivityid=userappactivityid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid=userid;
    }

    public int getAppid() {
        return appid;
    }

    public void setAppid(int appid) {
        this.appid=appid;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year=year;
    }

    public int getMonth() {
        return month;
    }

    public void setMonth(int month) {
        this.month=month;
    }

    public boolean getIsinstall() {
        return isinstall;
    }

    public void setIsinstall(boolean isinstall) {
        this.isinstall=isinstall;
    }

    public boolean getIsuninstall() {
        return isuninstall;
    }

    public void setIsuninstall(boolean isuninstall) {
        this.isuninstall=isuninstall;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date=date;
    }
}
