package com.fbdblog.dao;

import com.fbdblog.dao.hibernate.BasePersistentClass;
import com.fbdblog.dao.hibernate.RegerEntity;
import com.fbdblog.dao.hibernate.AuthControlled;
import com.fbdblog.dao.hibernate.HibernateUtil;
import com.fbdblog.util.GeneralException;

import java.util.Set;
import java.util.HashSet;

import org.apache.log4j.Logger;

/**
 * Survey generated by hbm2java
 */

public class Userappsettings extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {



     // Fields
     private int userappsettingsid;
     private int userid;
     private int appid;
     private boolean isprivate;




    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Userappsettings get(int id) {
        Logger logger = Logger.getLogger("com.fbdblog.dao.Userappsettings");
        try {
            logger.debug("Userappsettings.get(" + id + ") called.");
            Userappsettings obj = (Userappsettings) HibernateUtil.getSession().get(Userappsettings.class, id);
            if (obj == null) {
                logger.debug("Userappsettings.get(" + id + ") returning new instance because hibernate returned null.");
                return new Userappsettings();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.fbdblog.dao.Userappsettings", ex);
            return new Userappsettings();
        }
    }

    // Constructors

    /** default constructor */
    public Userappsettings() {
    }




    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }







    // Property accessors


    public int getUserappsettingsid() {
        return userappsettingsid;
    }

    public void setUserappsettingsid(int userappsettingsid) {
        this.userappsettingsid=userappsettingsid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid=userid;
    }

    public int getAppid() {
        return appid;
    }

    public void setAppid(int appid) {
        this.appid=appid;
    }

    public boolean getIsprivate() {
        return isprivate;
    }

    public void setIsprivate(boolean isprivate) {
        this.isprivate=isprivate;
    }


}
