package com.fbdblog.dao;

import com.fbdblog.dao.hibernate.BasePersistentClass;
import com.fbdblog.dao.hibernate.RegerEntity;
import com.fbdblog.dao.hibernate.HibernateUtil;
import com.fbdblog.dao.hibernate.AuthControlled;
import com.fbdblog.util.GeneralException;

import java.util.Date;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Userpersistentlogin extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


    // Fields
     private int userpersistentloginid;
     private int userid;
     private String randomstring;
     private Date lastusedtologin;


    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Userpersistentlogin get(int id) {
        Logger logger = Logger.getLogger("com.fbdblog.dao.Userpersistentlogin");
        try {
            logger.debug("Userpersistentlogin.get(" + id + ") called.");
            Userpersistentlogin obj = (Userpersistentlogin) HibernateUtil.getSession().get(Userpersistentlogin.class, id);
            if (obj == null) {
                logger.debug("Userpersistentlogin.get(" + id + ") returning new instance because hibernate returned null.");
                return new Userpersistentlogin();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.fbdblog.dao.Userpersistentlogin", ex);
            return new Userpersistentlogin();
        }
    }

    // Constructors

    /** default constructor */
    public Userpersistentlogin() {
    }

    public boolean canRead(User user){
        if (user.getUserid()==userid){
            return true;
        }
        return false;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors


    public int getUserpersistentloginid() {
        return userpersistentloginid;
    }

    public void setUserpersistentloginid(int userpersistentloginid) {
        this.userpersistentloginid = userpersistentloginid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }

    public String getRandomstring() {
        return randomstring;
    }

    public void setRandomstring(String randomstring) {
        this.randomstring = randomstring;
    }

    public Date getLastusedtologin() {
        return lastusedtologin;
    }

    public void setLastusedtologin(Date lastusedtologin) {
        this.lastusedtologin = lastusedtologin;
    }
}
